// <auto-generated />
namespace JJTrailer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class carousel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(carousel));
        
        string IMigrationMetadata.Id
        {
            get { return "201503051534349_carousel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
